### ISSUE TITLE
Up/Downvote

### ISSUE THREAD

**Issue by tom-richter** [qurry/qurry#10]
Questions
- [x] Backend Routes: /questions/<id>/?vote={-1,0,1}
- [x] Frontend Buttons
- [x] send `userVote: {-1,0,1}` in question json

Answers
- [x] Backend Routes: /questions/<id>/answers/<id>/?vote={-1,0,1}
- [x] Frontend Buttons
- [x] send `userVote: {-1,0,1}` in answer in question json

- Votes for comments in the future?

**Comment by tom-richter** [comment]
Frontend wasn't done :D

**Comment by AbdullatifGhajar** [comment]
983348f0941b6580eb01c1e04d8895c197a69d58

**Comment by tom-richter** [comment]
fixed in 73aed0322166277da02cce61a23ae7a6ad439c3c
