### ISSUE TITLE
CRUD Comments

### ISSUE THREAD

**Issue by tom-richter** [qurry/qurry#14]
Backend:
- [x] create/edit/delete comments

Frontend:
- [x] create/edit/delete comments

**Comment by AbdullatifGhajar** [comment]
6a95266424f60602de28a97f2af86d7c86e855e8
945324a528216f77cfe785b058ab098c266a3ed8

**Comment by tom-richter** [comment]
fixed in c59d2ac1d4244c8aba745e549da07dad1e780cd5
