### ISSUE TITLE
Add backslash to all routes in front and backend

### ISSUE THREAD

**Issue by tom-richter** [qurry/qurry#4]

**Comment by tom-richter** [comment]
For some strange reason this issue appears only with certain number like 1, 6 or 7.

**Comment by AbdullatifGhajar** [comment]
The backend part of this issue is closed

**Comment by AbdullatifGhajar** [comment]
- [ ] backend
- [ ] frontend

**Comment by tom-richter** [comment]
fixed in #61c6917bd6c3ee236f9dcd85b98e5713efc6b955
